create table prdwa17_ml.inference_nbview distribute by hash(CODE_VIDEO) AS
select CODE_VIDEO,
avg(T_VIEWCOUNT) as VIEWCOUNT,
avg(T_LIKECOUNT) as LIKECOUNT,
avg(T_CHANNELSUBSCRIBERCOUNT) as CHANNELSUBSCRIBERCOUNT,
avg(T_CHANNELVIDEOCOUNT) as CHANNELVIDEOCOUNT,
avg(T_COMMENTCOUNT) as COMMENTCOUNT,
avg(T_DISLIKECOUNT) as DISLIKECOUNT
from prdwa17_target.T_VIDEOFACTS
group by CODE_VIDEO;